### PR TITLE
Create for Hacktoberfest2024 lychrel_using_196_algo.py

### PR DESCRIPTION
**Pull request by 0mehedihasan**
Lychrel Test: The lychrel_test function implements the 196-algorithm. It reverses a number's digits and adds them iteratively, checking for a palindrome. If a palindrome is found within max_iterations, it returns False (indicating it's not a Lychrel number). If no palindrome is found, it assumes the number may be a Lychrel.

### CODE REVIEW

**Comment by extinctsion** [comment]
Thanks for your contribution in hacktoberfest. I'll label this PR as hacktoberfest-accepted and merge it. I was also thinking to make a website where we will be able to visualise the lychrel number problem. What do you say @0mehedihasan ?

**Comment by 0mehedihasan** [comment]
Sounds good to me.lets do it.
𝐁𝐞𝐬𝐭 𝐫𝐞𝐠𝐚𝐫𝐝𝐬,
𝐌𝐝 𝐌𝐞𝐡𝐞𝐝𝐢 𝐇𝐚𝐬𝐚𝐧
𝐕𝐢𝐜𝐞-𝐂𝐡𝐢𝐞𝐟, 𝐈𝐄𝐄𝐄 𝐂𝐒 𝐁𝐃𝐂 𝐓𝐞𝐚𝐦 𝐒𝐩𝐚𝐫𝐤
𝐕𝐢𝐜𝐞-𝐂𝐡𝐚𝐢𝐫𝐩𝐞𝐫𝐬𝐨𝐧, 𝐈𝐄𝐄𝐄 𝐂𝐒 𝐁𝐔𝐁𝐓 𝐒𝐁𝐂
𝐈𝐄𝐄𝐄 𝐌𝐞𝐦𝐛𝐞𝐫𝐬𝐡𝐢𝐩 𝐈𝐃: 98836293
𝐒𝐭𝐮𝐝𝐞𝐧𝐭 𝐚𝐭 𝐃𝐞𝐩𝐚𝐫𝐭𝐦𝐞𝐧𝐭 𝐨𝐟 𝐂𝐒𝐄,
𝐁𝐚𝐧𝐠𝐥𝐚𝐝𝐞𝐬𝐡 𝐔𝐧𝐢𝐯𝐞𝐫𝐬𝐢𝐭𝐲 𝐨𝐟 𝐁𝐮𝐬𝐢𝐧𝐞𝐬𝐬 𝐚𝐧𝐝
𝐓𝐞𝐜𝐡𝐧𝐨𝐥𝐨𝐠𝐲 (𝐁𝐔𝐁𝐓)
𝐒𝐭𝐮𝐝𝐞𝐧𝐭 𝐈𝐃: 212543103334

**Comment by extinctsion** [comment]
what is you preferred tech-stack? lets discuss it? Lets connect via LinkedIn. What do you say?

**Comment by 0mehedihasan** [comment]
Regarding my preferred tech stack, I usually work with Java, C,C++,JSP,
HTML, CSS, and JavaScript for frontend and backend development. I'm also
open to using Python if we need to implement more complex algorithms or
data visualizations.
Linkedin:
https://www.linkedin.com/in/0mehedihasan?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

𝐁𝐞𝐬𝐭 𝐫𝐞𝐠𝐚𝐫𝐝𝐬,
𝐌𝐝 𝐌𝐞𝐡𝐞𝐝𝐢 𝐇𝐚𝐬𝐚𝐧
𝐕𝐢𝐜𝐞-𝐂𝐡𝐢𝐞𝐟, 𝐈𝐄𝐄𝐄 𝐂𝐒 𝐁𝐃𝐂 𝐓𝐞𝐚𝐦 𝐒𝐩𝐚𝐫𝐤
𝐕𝐢𝐜𝐞-𝐂𝐡𝐚𝐢𝐫𝐩𝐞𝐫𝐬𝐨𝐧, 𝐈𝐄𝐄𝐄 𝐂𝐒 𝐁𝐔𝐁𝐓 𝐒𝐁𝐂
𝐈𝐄𝐄𝐄 𝐌𝐞𝐦𝐛𝐞𝐫𝐬𝐡𝐢𝐩 𝐈𝐃: 98836293
𝐒𝐭𝐮𝐝𝐞𝐧𝐭 𝐚𝐭 𝐃𝐞𝐩𝐚𝐫𝐭𝐦𝐞𝐧𝐭 𝐨𝐟 𝐂𝐒𝐄,
𝐁𝐚𝐧𝐠𝐥𝐚𝐝𝐞𝐬𝐡 𝐔𝐧𝐢𝐯𝐞𝐫𝐬𝐢𝐭𝐲 𝐨𝐟 𝐁𝐮𝐬𝐢𝐧𝐞𝐬𝐬 𝐚𝐧𝐝
𝐓𝐞𝐜𝐡𝐧𝐨𝐥𝐨𝐠𝐲 (𝐁𝐔𝐁𝐓)
𝐒𝐭𝐮𝐝𝐞𝐧𝐭 𝐈𝐃: 212543103334

**Comment by extinctsion** [comment]
That's old I guess. Lets use something like Next.js which is new in the market.

**Pull request merged**
